[package]
name = "sjc"
version = "0.1.0"
authors = ["Sam Westerman <sam@sampersand.me>"]
edition = "2018"
description = "Sojourn's Compiler"

[dependencies]
sjef = { path = "../sjef", version = "*" }
