[package]
name = 'sjvm'
version = '0.1.0'
authors = ['Sam Westerman <sam@sampersand.me>']
edition = '2018'

[dependencies]
static_assertions = '1.1'
bitflags = '1.2.1'
read-from = "^0.5"
tracing = "0.1"
